#name = Piton
#language = Spanish
#keywords
and y
as como
assert afirme
break quebre
class clase
continue siga
def def
del elim
elif sinosi
else sino
except excepto
exec ejec
finally finalmente
for para
from de
global mundial
if si
import importe
in en
is es
lambda lambda
not no
or o
pass pase
print imprima
raise suba
return devuelva
try intente
while mientras
with con
yield ceda
True Cierto
False Falso
self mismo
#built in functions
abs abs
all todos
any cualquier
basestring basecadena
bin bin
bool bool
bytearray bytematriz
callable remidible
chr car
classmethod clasemetodo
cmp cmp
compile recopile
complex coplejo
delattr elimatrib
dict dicc
dir guia
divmod divmod
enumerate enumera
eval valore
execfile ejecarchivo
file archivo
filter filtre
float flote
format formatee
frozenset collecioncongelado
getattr obtengaatr
globals mundiales
hasattr tieneatr
hash hash
help ayude
hex hex
id id
input registre
int ent
isinstance esocasion
issubclass essubclase
iter iter
len longitud
list lista
locals locales
long largo
map mapa
max max
memoryview memoriavista
min min
next proximo
object objeto
oct oct
open abra
ord ord
pow elev
property propiedad
range gama
raw_input crudo_registre
reduce reduzca
reload recargue
repr repr
reversed opuesto
round redondee
set pon
setattr ponatrib
slice corte
sorted ordenado
staticmethod estaticometodo
str cadena
super super
tuple tuple
type tipo
unichr unicar
unicode unicodigo
vars vars
xrange xgama
zip cierre
#built in errors
Exception Excepcion
BaseException ExcepcionDeBase
StandardError ErrorComun
ArithmeticError ErrorDeAritmetica
BufferError ErrorDeBufer
LookupError ErrorDeBuscar
EnvironmentError ErrorDeAmbiente
AssertionError ErrorDeAseveracion
AttributeError ErrorDeAtributo
EOFError ErrorDeFDA
FloatingPointError ErrorDePuntoFlotante
GeneratorExit SalidaDeGenerador
IOError ErrorDeER
ImportError ErrorDeImportar
IndexError ErrorDeIndice
KeyError ErrorDeLlave
KeyboardInterrupt InterrupcionDeTeclado
MemoryError ErrorDeMemoria
NameError ErrorDeNombre
NotImplementedError ErrorDeNoImplementado
OSError ErrorDeSO
OverflowError ErrorDeSobrante
ReferenceError ErrorDeFuente
RuntimeError ErrorDeCorrer
StopIteration ParaIteracion
SyntaxError ErrorDeSintaxis
IndentationError ErrorDeSangria
TabError ErrorDeTab
SystemError ErrorDeSistema
SystemExit SalidaDeSistema
TypeError ErrorDeTipo
UnboundLocalError ErrorDeSueltoLocal
UnicodeError ErrorDeUnicode
UnicodeEncodeError ErrorDeCodificarUnicode
UnicodeDecodeError ErrorDeDescodificarUnicode
UnicodeTranslateError ErrorDeTraducirUnicode
ValueError ErrorDeValor
WindowsError ErrorDeVentanas
ZeroDivisionError ErrorDeDividirCero
Warning Alarma
UserWarning AlarmaDeUsuario
DeprecationWarning AlarmaDeDesprecio
PendingDeprecationWarning AlarmaDePendienteDesprecio
SyntaxWarning AlarmaDeSintaxis
RuntimeWarning AlarmaDeCorrer
FutureWarning AlarmaDeFuturo
ImportWarning AlarmaDeImportar
UnicodeWarning AlarmaDeUnicode
#default modules
#time
time tiempo
clock reloj
ctime ctiempo
daylight horasdeluz
gmtime gmtiempo
localtime tiempolocal
mktime haztiempo
sleep duerma
strftime cadena_de_tiempo
strptime cadena_a_tiempo
struct_time esquema_tiempo
timezone zonahoraria
tzname zhnombre
tzset zhpon
